"""autogen check

Revision ID: 001ef74a7d34
Revises: 86e716e20261
Create Date: 2026-02-09 12:48:56.506726

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "001ef74a7d34"
down_revision: str | Sequence[str] | None = "86e716e20261"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
