"""add audit_events

Revision ID: aa531b0137b1
Revises: 35fb63a9269f
Create Date: 2026-02-10 12:02:33.956705

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa531b0137b1"
down_revision: str | Sequence[str] | None = "35fb63a9269f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.alter_column(
            "region",
            existing_type=sa.VARCHAR(length=10),
            type_=sa.String(length=8),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "actor_id",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            nullable=False,
        )
        batch_op.alter_column(
            "actor_type", existing_type=sa.VARCHAR(length=32), nullable=False
        )
        batch_op.alter_column(
            "tenant_id",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "resource", existing_type=sa.VARCHAR(length=128), nullable=False
        )
        batch_op.alter_column(
            "outcome",
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=16),
            nullable=False,
        )
        batch_op.alter_column("status_code", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "ip",
            existing_type=sa.VARCHAR(length=45),
            type_=sa.String(length=64),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.alter_column(
            "ip",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=45),
            existing_nullable=True,
        )
        batch_op.alter_column("status_code", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "outcome",
            existing_type=sa.String(length=16),
            type_=sa.VARCHAR(length=32),
            nullable=True,
        )
        batch_op.alter_column(
            "resource", existing_type=sa.VARCHAR(length=128), nullable=True
        )
        batch_op.alter_column(
            "tenant_id",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "actor_type", existing_type=sa.VARCHAR(length=32), nullable=True
        )
        batch_op.alter_column(
            "actor_id",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            nullable=True,
        )
        batch_op.alter_column(
            "region",
            existing_type=sa.String(length=8),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
