"""add user mfa fields

Revision ID: ee8ef3a2fe88
Revises: 4120445d3511
Create Date: 2026-02-25 07:59:06.348668

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee8ef3a2fe88"
down_revision: str | Sequence[str] | None = "4120445d3511"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "mfa_enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),  # <-- critical for SQLite + existing rows
            )
        )

    # Optional cleanup: drop the default so new rows rely on ORM default only
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("mfa_enabled", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("mfa_secret")
        batch_op.drop_column("mfa_enabled")

    # ### end Alembic commands ###
